services:
  python-app:
    build:
      context: .
    container_name: python-app
    restart: unless-stopped
    init: true
    # env_file: ./.env  # Uncomment if .env file exists
    ports:
      - "5000:5000"  # Expose Flask default port
    # If you add a database or other services, add depends_on here
    # networks: [appnet]  # Uncomment if you add more services/networks

# No external services (databases, caches, etc.) detected in the project documentation or code.
# No volumes section needed as there are no persistent data services.
# No custom networks needed for a single service.
