version: '3'

services:
  gorilla-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=local-dev-key-replace-in-production
      - FLASK_DEBUG=True
      - MONGODB_URI=mongodb://mongo:27017/gorillacamping
      - AI_PROVIDER=gemini
      - GEMINI_API_KEY=your-dev-api-key
      - STATIC_SITE_URL=http://localhost:5000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
